services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: gaurav
      MYSQL_PASSWORD: gaurav
    ports:
      - "3306:3306"